# fly.toml file generated for aurora-borealis on 2023-03-01T02:32:22+02:00

app = "aurora-borealis"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  cron = "supercronic /usr/local/app/crontab"

[env]

[experimental]
  auto_rollback = true
