# fly.toml file generated for aurora-borealis on 2023-03-01T02:32:22+02:00

app = "aurora-borealis"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[processes]
  app = ""
  cron = "cron -f"
  worker = ""

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = []
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
